-- Основная таблица игр
CREATE TABLE games (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      state VARCHAR(50) NOT NULL
);

-- Таблица связи игры и игроков
CREATE TABLE game_players (
      game_id BIGINT NOT NULL,
      player_id BIGINT NOT NULL,
      PRIMARY KEY (game_id, player_id),
      CONSTRAINT fk_game
          FOREIGN KEY (game_id)
              REFERENCES games(id)
              ON DELETE CASCADE
);