CREATE TABLE IF NOT EXISTS outbox_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aggregate_type VARCHAR(100) NOT NULL,   -- тип агрегата, например "PLAYER"
    aggregate_id VARCHAR(100) NOT NULL,     -- id агрегата
    event_type VARCHAR(50) NOT NULL,        -- тип события, например "PLAYER_JOINED_GAME"
    payload CLOB NOT NULL,                 -- данные события в формате JSON
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now(),
    published BOOLEAN DEFAULT false
 );