-- Таблица юнитов
CREATE TABLE IF NOT EXISTS units (
       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
       type VARCHAR(50),
       x DOUBLE PRECISION,
       y DOUBLE PRECISION,
       owner_id BIGINT,
       game_id BIGINT,
       health INTEGER
);