spring:
  application:
    name: event-service

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: event-service-group
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

grpc:
  server:
    port: 9094